### ISSUE TITLE
 Unable to start activity ComponentInfo，gradle配置也相同，引入之后就是运行不起来

### ISSUE THREAD

**Issue by zwping** [yuzhiqiang1993/zxing#113]
java.lang.RuntimeException: Unable to start activity ComponentInfo{lvbu.wang.lvbuoperator/com.yzq.zxinglibrary.android.CaptureActivity}: android.view.InflateException: Binary XML file line #14: Binary XML file line #14: Error inflating class lvbu.wang.lvbuoperator.zxing.view.ViewfinderView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3303)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: android.view.InflateException: Binary XML file line #14: Binary XML file line #14: Error inflating class lvbu.wang.lvbuoperator.zxing.view.ViewfinderView
     Caused by: android.view.InflateException: Binary XML file line #14: Error inflating class lvbu.wang.lvbuoperator.zxing.view.ViewfinderView
2019-03-17 15:30:51.510 21050-21050/lvbu.wang.lvbuoperator E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "lvbu.wang.lvbuoperator.zxing.view.ViewfinderView" on path: DexPathList[[zip file "/data/app/lvbu.wang.lvbuoperator-DEKUyn0-hE94JIUHK7L5CA==/base.apk", zip file "/data/app/lvbu.wang.lvbuoperator-DEKUyn0-hE94JIUHK7L5CA==/split_lib_dependencies_apk.apk", zip file "/data/app/lvbu.wang.lvbuoperator-DEKUyn0-hE94JIUHK7L5CA==/split_lib_resources_apk.apk", zip file "/data/app/lvbu.wang.lvbuoperator-DEKUyn0-hE94JIUHK7L5CA==/split_lib_slice_0_apk.apk", zip file "/data/app/lvbu.wang.lvbuoperator-DEKUyn0-hE94JIUHK7L5CA==/split_lib_slice_1_apk.apk", zip file "/data/app/lvbu.wang.lvbuoperator-DEKUyn0-hE94JIUHK7L5CA==/split_lib_slice_2_apk.apk", zip file "/data/app/lvbu.wang.lvbuoperator-DEKUyn0-hE94JIUHK7L5CA==/split_lib_slice_3_apk.apk", zip file "/data/app/lvbu.wang.lvbuoperator-DEKUyn0-hE94JIUHK7L5CA==/split_lib_slice_4_apk.apk", zip file "/data/app/lvbu.wang.lvbuoperator-DEKUyn0-hE94JIUHK7L5CA==/split_lib_slice_5_apk.apk", zip file "/data/app/lvbu.wang.lvbuoperator-DEKUyn0-hE94JIUHK7L5CA==/split_lib_slice_6_apk.apk", zip file "/data/app/lvbu.wang.lvbuoperator-DEKUyn0-hE94JIUHK7L5CA==/split_lib_slice_7_apk.apk", zip file "/data/app/lvbu.wang.lvbuoperator-DEKUyn0-hE94JIUHK7L5CA==/split_lib_slice_8_apk.apk", zip file "/data/app/lvbu.wang.lvbuoperator-DEKUyn0-hE94JIUHK7L5CA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/lvbu.wang.lvbuoperator-DEKUyn0-hE94JIUHK7L5CA==/lib/arm64, /data/app/lvbu.wang.lvbuoperator-DEKUyn0-hE94JIUHK7L5CA==/base.apk!/lib/arm64-v8a, /data/app/lvbu.wang.lvbuoperator-DEKUyn0-hE94JIUHK7L5CA==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/lvbu.wang.lvbuoperator-DEKUyn0-hE94JIUHK7L5CA==/split_lib_resources_apk.apk!/lib/arm64-v8a, /data/app/lvbu.wang.lvbuoperator-DEKUyn0-hE94JIUHK7L5CA==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/lvbu.wang.lvbuoperator-DEKUyn0-hE94JIUHK7L5CA==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/lvbu.wang.lvbuoperator-DEKUyn0-hE94JIUHK7L5CA==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/lvbu.wang.lvbuoperator-DEKUyn0-hE94JIUHK7L5CA==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/lvbu.wang.lvbuoperator-DEKUyn0-hE94JIUHK7L5CA==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/lvbu.wang.lvbuoperator-DEKUyn0-hE94JIUHK7L5CA==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/lvbu.wang.lvbuoperator-DEKUyn0-hE94JIUHK7L5CA==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/lvbu.wang.lvbuoperator-DEKUyn0-hE94JIUHK7L5CA==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/lvbu.wang.lvbuoperator-DEKUyn0-hE94JIUHK7L5CA==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/lvbu.wang.lvbuoperator-DEKUyn0-hE94JIUHK7L5CA==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.view.LayoutInflater.createView(LayoutInflater.java:613)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:801)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.yzq.zxinglibrary.android.CaptureActivity.onCreate(CaptureActivity.java:108)
        at android.app.Activity.performCreate(Activity.java:7383)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)

**Comment by yuzhiqiang1993** [comment]
你的引入方式是什么，从日志来看应该是包名的问题

**Comment by zwping** [comment]
已经本地化了，正在查找问题所在

之前这个项目有引入过zxing，有去掉且删掉了build等文件

**Comment by yuzhiqiang1993** [comment]
那应该是冲突了，你可以参考下下面这篇文章，主要应该是路径的问题。https://blog.csdn.net/yuzhiqiang_1993/article/details/52805057

**Comment by zwping** [comment]
一提issues就解决了，是layout名字重复

**Comment by zwping** [comment]
thx
