### ISSUE TITLE
Monkey测试出报空指针错误

### ISSUE THREAD

**Issue by 13568810905** [yuzhiqiang1993/zxing#119]
魅蓝 移动4G M1 android 4.4.4
```
java.lang.NullPointerException: java.lang.NullPointerException
	at com.yzq.zxinglibrary.camera.CameraManager.switchFlashLight(CameraManager.java:171)
	at com.yzq.zxinglibrary.android.CaptureActivity.onClick(CaptureActivity.java:326)
	at android.view.View.performClick(View.java:4652)
	at android.view.View$PerformClick.run(View.java:19429)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5348)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
```

**Comment by yuzhiqiang1993** [comment]
请问是最新版本吗？

**Comment by 13568810905** [comment]
测试用的是2.5.5的，之前添加依赖的时候还没有发新版本，等下我更新了再测一次

**Comment by 13568810905** [comment]
更新到2.2.7后没问题了
