### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by RuijinYao** [yuzhiqiang1993/zxing#120]
老哥，空指针异常啊：
就用最简单Intent intent = new Intent(MainActivity.this, CaptureActivity.class);调用扫面界面，
添加了相关的相机权限后点击打开闪光灯就会报错闪退啊，
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
        at com.yzq.zxinglibrary.android.CaptureActivity.switchFlashImg(CaptureActivity.java:180)
        at com.yzq.zxinglibrary.android.CaptureActivityHandler.handleMessage(CaptureActivityHandler.java:93)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:159)
        at android.app.ActivityThread.main(ActivityThread.java:6364)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)

**Comment by RuijinYao** [comment]
额，自己解决了，练习的时候按照博客地址https://blog.csdn.net/ky1996/article/details/79502358这边demo的写的，gradle添加依赖版本2.2.1才导致的，修改依赖版本到2.2.7就没这个问题了。

**Comment by yuzhiqiang1993** [comment]
好的
