### ISSUE TITLE
在Fragment启动崩溃

### ISSUE THREAD

**Issue by wangchengnuo** [yuzhiqiang1993/zxing#125]
@Override
    public void onActivityCreated(@Nullable Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
        scanButton.setOnClickListener(new View.OnClickListener(){

            @Override
            public void onClick(View view) {
                Intent intent = new Intent(getActivity(), CaptureActivity.class);
                getActivity().startActivityForResult(intent, REQUEST_CODE_SCAN);
            }
        });
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        // 扫描二维码/条码回传
        if (requestCode == REQUEST_CODE_SCAN && resultCode == RESULT_OK) {
            if (data != null) {

                String content = data.getStringExtra(Constant.CODED_CONTENT);
                Toast.makeText(getContext(), "扫描成功", Toast.LENGTH_SHORT).show();
                //result.setText("扫描结果为：" + content);
            }
        }
    }

**Comment by yuzhiqiang1993** [comment]
具体的报错信息有吗

**Comment by wangchengnuo** [comment]
FATAL EXCEPTION: main
                                                                                              Process: com.bignerdranch.android.containermanagesystem, PID: 3217
                                                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bignerdranch.android.containermanagesystem/com.yzq.zxinglibrary.android.CaptureActivity}: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
                                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2327)
                                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
                                                                                                  at android.app.ActivityThread.access$800(ActivityThread.java:153)
                                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1305)
                                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5293)
                                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                                               Caused by: java.lang.RuntimeException: A TaskDescription's primary color should be opaque

**Comment by yuzhiqiang1993** [comment]
是最新版本的吗

**Comment by wangchengnuo** [comment]
SDK 26

**Comment by yuzhiqiang1993** [comment]
库的版本呢？是2.2.8吗？

**Comment by wangchengnuo** [comment]
2.1.4

**Comment by yuzhiqiang1993** [comment]
用2.2.8试一下，这个问题解决过

**Comment by wangchengnuo** [comment]
可以跳转intent了，但是报这个错
W/com.yzq.zxinglibrary.camera.OpenCameraInterface: No cameras!
是因为我的模拟器没有相机吗

**Comment by yuzhiqiang1993** [comment]
权限给了吗？可能是权限没处理，要么就是获取不到摄像头，建议用真机测试

**Comment by wangchengnuo** [comment]
if(ContextCompat.checkSelfPermission(getActivity(),Manifest.
                        permission.CAMERA) != PackageManager.PERMISSION_GRANTED){
                    ActivityCompat.requestPermissions(getActivity(), new String[]{Manifest.permission.CAMERA}, 1);
                }else{
                    Intent intent = new Intent(getActivity(), CaptureActivity.class);
                    getActivity().startActivityForResult(intent, REQUEST_CODE_SCAN);
                }
这是动态权限，静态权限也给了

**Comment by yuzhiqiang1993** [comment]
那估计是获取不到模拟器的摄像头，用真机试试

**Comment by wangchengnuo** [comment]
好的，谢谢大佬
