### ISSUE TITLE
大神,用了各种办法还是不识别vector咋办

### ISSUE THREAD

**Issue by 291693420** [yuzhiqiang1993/zxing#13]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.emcshare.manager/com.yzq.zxinglibrary.android.CaptureActivity}: android.view.InflateException: Binary XML file line #0: Error inflating class android.support.v7.widget.AppCompatImageView
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2264)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313)
                                                                          at android.app.ActivityThread.access$1100(ActivityThread.java:141)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:136)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5336)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:873)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
                                                                          at dalvik.system.NativeStart.main(Native Method)
                                                                       Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class android.support.v7.widget.AppCompatImageView
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:640)
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:775)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:778)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:778)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:778)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:512)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:409)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:358)
                                                                          at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290)
                                                                          at android.app.Activity.setContentView(Activity.java:1968)
                                                                          at com.yzq.zxinglibrary.android.CaptureActivity.onCreate(CaptureActivity.java:101)
                                                                          at android.app.Activity.performCreate(Activity.java:5302)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2228)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313) 
                                                                          at android.app.ActivityThread.access$1100(ActivityThread.java:141) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:136) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5336) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:873) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689) 
                                                                          at dalvik.system.NativeStart.main(Native Method) 
                                                                       Caused by: java.lang.reflect.InvocationTargetException
                                                                          at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                          at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:614)
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:775) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:778) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:778) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:778) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:512) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:409) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:358) 
                                                                          at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290) 
                                                                          at android.app.Activity.setContentView(Activity.java:1968) 
                                                                          at com.yzq.zxinglibrary.android.CaptureActivity.onCreate(CaptureActivity.java:101) 
                                                                          at android.app.Activity.performCreate(Activity.java:5302) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2228) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313) 
                                                                          at android.app.ActivityThread.access$1100(ActivityThread.java:141) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:136) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5336) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:873) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689) 
                                                                          at dalvik.system.NativeStart.main(Native Method) 
                                                                       Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_close.xml from drawable resource ID #0x7f07008b
                                                                          at android.content.res.Resources.loadDrawable(Resources.java:2154)
                                                                          at android.content.res.TypedArray.getDrawable(TypedArray.java:650)
                                                                          at android.widget.ImageView.<init>(ImageView.java:129)
                                                                          at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:72)
                                                                          at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:68)
                                                                          at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                          at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:614) 
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:775) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:778) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:778) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:778) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:512) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:409) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:358) 
                                                                          at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290) 
                                                                          at android.app.Activity.setContentView(Activity.java:1968) 
                                                                          at com.yzq.zxinglibrary.android.CaptureActivity.onCreate(CaptureActivity.java:101) 
                                                                          at android.app.Activity.performCreate(Activity.java:5302) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2228) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313) 
                                                                          at android.app.ActivityThread.access$1100(ActivityThread.java:141) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:136) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5336) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:873) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689) 
                                                                          at dalvik.system.NativeStart.main(Native Method) 
                                                                       Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #0: invalid drawable tag vector
                                                                          at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
                                                                          at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
                                                                          at android.content.res.Resources.loadDrawable(Resources.java:2150)
                                                                          at android.content.res.TypedArray.getDrawable(TypedArray.java:650) 
                                                                          at android.widget.ImageView.<init>(ImageView.java:129) 
                                                                          at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:72) 
                                                                          at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:68) 
                                                                          at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                          at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:614) 
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:775) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:778) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:778) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:778) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:512) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:409) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:358) 
                                                                          at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290) 
                                                                          at android.app.Activity.setContentView(Activity.java:1968) 
                                                                          at com.yzq.zxinglibrary.android.CaptureActivity.onCreate(CaptureActivity.java:101) 
                                                                          at android.app.Activity.performCreate(Activity.java:5302) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2228) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313) 
                                                                          at android.app.ActivityThread.access$1100(ActivityThread.java:141) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:136) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5336) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:873) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689) 
                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by yuzhiqiang1993** [comment]
在你的application类中的oncreate中添加    AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);
试试。

**Comment by 291693420** [comment]
还是那个错误,我适配的手机系统是android4.4的,我在gradle里加了vectorDrawables.useSupportLibrary = true,  compile 'com.android.support:support-vector-drawable:26.1.0'   也在application设置了AppCompatDelegate.setCompatVectorFromResourcesEnabled(true),还是不行

**Comment by yuzhiqiang1993** [comment]
你的gradle版本是多少?

**Comment by 291693420** [comment]
classpath 'com.android.tools.build:gradle:3.0.1'

**Comment by 291693420** [comment]
android studio 3.0.1
gradle version 4.1
android plugin version 3.0.1

**Comment by yuzhiqiang1993** [comment]
好的  我明天看一下

**Comment by yuzhiqiang1993** [comment]
你好，麻烦测试一下2.1.1版本，感谢！
 implementation 'com.github.yuzhiqiang1993:zxing:2.1.1'

**Comment by 291693420** [comment]
谢谢，我待会试下

**Comment by 291693420** [comment]
可以了，谢谢大神，不过我的as使用implementation 'com.github.yuzhiqiang1993:zxing:2.1.1'不能编译通过，使用compile 'com.github.yuzhiqiang1993:zxing:2.1.1'才行

**Comment by yuzhiqiang1993** [comment]
编译不通过是报什么错呢？

**Comment by 291693420** [comment]
import com.yzq.zxinglibrary.android.CaptureActivity;
import com.yzq.zxinglibrary.common.Constant;
这两行报错，找不到类

**Comment by yuzhiqiang1993** [comment]
哦  那你应该把implementation 改成api

**Comment by 291693420** [comment]
okk

**Comment by yuzhiqiang1993** [comment]
我这边自己测试使用的implementation 也是没问题的

**Comment by 291693420** [comment]
我明白了，我把你的这个库放到公用的library里面了，所以implementation本身的用法就会导致找不到

**Comment by yuzhiqiang1993** [comment]
对的，如果你作为module使用时，就要用api了
