### ISSUE TITLE
找不到 资源文件 崩溃 

### ISSUE THREAD

**Issue by wjygg** [yuzhiqiang1993/zxing#130]
android.content.res.Resources$NotFoundException: Resource ID #0x7f080174
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:279)
        at android.content.res.Resources.getDimensionPixelSize(Resources.java:790)
        at com.yzq.zxinglibrary.camera.CameraManager.buildLuminanceSource(CameraManager.java:364)
        at com.yzq.zxinglibrary.decode.DecodeHandler.decode(DecodeHandler.java:86)
        at com.yzq.zxinglibrary.decode.DecodeHandler.handleMessage(DecodeHandler.java:57)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at com.yzq.zxinglibrary.decode.DecodeThread.run(DecodeThread.java:85)

插件依赖 toolBarHeight 资源高度找不到 崩溃

**Comment by yuzhiqiang1993** [comment]
扫码下载apk运行也会崩溃吗？

**Comment by wjygg** [comment]
插件化开发  插件依赖类库打开扫 activity 崩溃        直接下载直接运行没有问题

**Comment by wjygg** [comment]
int actionbarHeight = this.context.getResources().getDimensionPixelSize(dimen.toolBarHeight);   cameraManager 里面 这一行找不到资源报错

**Comment by yuzhiqiang1993** [comment]
直接依赖使用出现的这个问题吗？没有修改过代码吧
