### ISSUE TITLE
扫描页面黑屏无法扫描 点击打开闪光灯后崩溃

### ISSUE THREAD

**Issue by skpy5272** [yuzhiqiang1993/zxing#149]
扫描页面黑屏无法扫描 点击打开闪光灯后崩溃 日志显示是cameraManager 中Camera 空

**Comment by yuzhiqiang1993** [comment]
有具体报错信息吗?

**Comment by eternallyjie** [comment]
你好，我这也时遇到开闪光灯就崩溃，下面是报上来的报错信息：
java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference
	at com.yzq.zxinglibrary.camera.CameraManager.switchFlashLight(CameraManager.java:170)
	at com.yzq.zxinglibrary.android.CaptureActivity.onClick(CaptureActivity.java:324)
	at android.view.View.performClick(View.java:6387)
	at android.view.View$PerformClick.run(View.java:25217)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7014)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:514)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)

**Comment by eternallyjie** [comment]
> 有具体报错信息吗?

你好，我也遇到过打开闪光灯就崩溃的情况，下面是提交上来的报错信息：
java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference
	at com.yzq.zxinglibrary.camera.CameraManager.switchFlashLight(CameraManager.java:170)
	at com.yzq.zxinglibrary.android.CaptureActivity.onClick(CaptureActivity.java:324)
	at android.view.View.performClick(View.java:6387)
	at android.view.View$PerformClick.run(View.java:25217)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7014)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:514)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)

**Comment by skpy5272** [comment]
> 有具体报错信息吗?

恩呢，和那位朋友的一样

**Comment by Go-Jeon-Pa** [comment]
+1，不是很好复现
