### ISSUE TITLE
使用Android 5.1 版本的手机无法解码

### ISSUE THREAD

**Issue by RyoJerryYu** [yuzhiqiang1993/zxing#202]
使用Android 5.1 版本的手机，调用扫一扫界面扫描二维码或读取二维码图片时解码失败。

## 库版本

2.2.9

## 引入方式

使用Gradle引入
```
implementation 'com.github.yuzhiqiang1993:zxing:2.2.9'
```

## 测试环境

华为SCL-TL00H（EMUI系统 3.1），Android版本5.1.1

Gradle中Sdk设置
```
android {
    compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 30
        ...
    }
    ...
}
```

## 异常情况

调用扫一扫界面后，扫描二维码或读取二维码时，均会发生运行时异常。

## 异常信息

- 摄像头扫描二维码时异常信息如下：
  ```
  java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
      at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(FinderPatternFinder.java:624)
      at com.google.zxing.qrcode.detector.FinderPatternFinder.find(FinderPatternFinder.java:164)
      at com.google.zxing.qrcode.detector.Detector.detect(Detector.java:81)
      at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
      at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:173)
      at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:87)
      at com.yzq.zxinglibrary.decode.DecodeHandler.decode(DecodeHandler.java:93)
      at com.yzq.zxinglibrary.decode.DecodeHandler.handleMessage(DecodeHandler.java:57)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:135)
      at com.yzq.zxinglibrary.decode.DecodeThread.run(DecodeThread.java:80)
  ```
- 读取二维码文件后异常信息如下：
  ```
  java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
      at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(FinderPatternFinder.java:624)
      at com.google.zxing.qrcode.detector.FinderPatternFinder.find(FinderPatternFinder.java:164)
      at com.google.zxing.qrcode.detector.Detector.detect(Detector.java:81)
      at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
      at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:173)
      at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:87)
      at com.yzq.zxinglibrary.decode.DecodeImgThread.run(DecodeImgThread.java:64)
      at com.yzq.zxinglibrary.android.CaptureActivity.onActivityResult(CaptureActivity.java:361)
      at android.app.Activity.dispatchActivityResult(Activity.java:6320)
      at android.app.ActivityThread.deliverResults(ActivityThread.java:3836)
      at android.app.ActivityThread.handleSendResult(ActivityThread.java:3883)
      at android.app.ActivityThread.access$1700(ActivityThread.java:165)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1426)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:135)
      at android.app.ActivityThread.main(ActivityThread.java:5593)
      at java.lang.reflect.Method.invoke(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:372)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
  ```

## 可能原因

本项目2.2.9中引用了3.4.0以上版本的Zxing。而Zxing3.4.0以上版本最低只支持到Android7.0：

> Note that release 3.4.0 and later requires Java 8, which requires targeting API level 24 or later. For a possible way to use it with earlier API levels, see
 [https://github.com/zxing/zxing/wiki/Frequently-Asked-Questions#it-doesnt-work-with-java-7--no-interface-method-sortljavautilcomparator](https://github.com/zxing/zxing/wiki/Frequently-Asked-Questions#it-doesnt-work-with-java-7--no-interface-method-sortljavautilcomparator) 
or simply use an earlier release.

当应用需要兼容Android5.0版本的手机时，不能使用本项目2.2.9的版本。

**Comment by RyoJerryYu** [comment]
此问题为2.2.9中使用的Zxing3.4.0不兼容导致。
Android5.0版本要使用本项目可引入2.2.8或以下版本。
#203
