### ISSUE TITLE
不知道为什么出现这个错误，android 版本的问题？ A TaskDescription's primary color should be opaque

### ISSUE THREAD

**Issue by yanshaozhi** [yuzhiqiang1993/zxing#29]
`Process: com.yf.school, PID: 15352
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yf.school/com.yzq.zxinglibrary.android.CaptureActivity}: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
        at android.app.ActivityThread.access$1000(ActivityThread.java:153)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:5523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
     Caused by: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
        at android.app.ActivityManager$TaskDescription.<init>(ActivityManager.java:586)
        at android.app.Activity.onApplyThemeResource(Activity.java:3786)
        at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:150)
        at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:94)
        at android.support.v7.app.AppCompatActivity.setTheme(AppCompatActivity.java:89)`

**Comment by yuzhiqiang1993** [comment]
请问是在哪个android版本下出现的这个问题？
