### ISSUE TITLE
红米Note4  Android6.0 上出现 java.lang.RuntimeException: A TaskDescription's primary color should be opaque

### ISSUE THREAD

**Issue by kimlllll** [yuzhiqiang1993/zxing#31]
06-01 10:22:11.237 16995-16995/? E/CrashHandler: In thread: Thread[main,5,main]
                                                 UncaughtException detected: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.itdksandroid/com.yzq.zxinglibrary.android.CaptureActivity}: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2570)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2636)
                                                     at android.app.ActivityThread.access$1000(ActivityThread.java:180)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494)
                                                     at android.os.Handler.dispatchMessage(Handler.java:111)
                                                     at android.os.Looper.loop(Looper.java:207)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5811)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)
                                                  Caused by: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
                                                     at android.app.ActivityManager$TaskDescription.<init>(ActivityManager.java:631)
                                                     at android.app.Activity.onApplyThemeResource(Activity.java:3833)
                                                     at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:150)
                                                     at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:94)
                                                     at android.support.v7.app.AppCompatActivity.setTheme(AppCompatActivity.java:89)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2516)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2636) 
                                                     at android.app.ActivityThread.access$1000(ActivityThread.java:180) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                     at android.os.Looper.loop(Looper.java:207) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5811) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)

**Comment by kimlllll** [comment]
已解决
